CREATE TABLE EMPRESA(
	ID UNIQUEIDENTIFIER PRIMARY KEY,
	RAZAOSOCIAL VARCHAR(150) NOT NULL,
	CNPJ        VARCHAR(20)  NOT NULL,

 );

 CREATE TABLE FUNCIONARIO(
	ID UNIQUEIDENTIFIER PRIMARY KEY,
	NOME VARCHAR(100) NOT NULL,
	CPF VARCHAR(14) NOT NULL,
	MATRICULA VARCHAR(15) NOT NULL,
	DATAADMISSAO DATE NOT NULL,
	EMPRESAID UNIQUEIDENTIFIER NOT NULL,
	FOREIGN KEY(EMPRESAID) REFERENCES EMPRESA(ID)
 );

 SELECT * FROM EMPRESA;
 SELECT * FROM FUNCIONARIO;

 INSERT INTO EMPRESA(ID, RAZAOSOCIAL, CNPJ) VALUES (NEWID(), 'EMPRESA A', '32.696.834/0001-70')
 INSERT INTO EMPRESA(ID, RAZAOSOCIAL, CNPJ) VALUES (NEWID(), 'EMPRESA B', '61.735.979/0001-30')

